### ISSUE TITLE
interpretability?

### ISSUE THREAD

**Issue by koke2c95** [anthony-dipofi/danbooru-tagger#2]
### RELATED WORKS
[DeepDanbooru gradcam](https://github.com/halcy/DeepDanbooruActivationMaps)

[openai microscope](https://microscope.openai.com/models)
[pytorch lucid](https://github.com/greentfrapp/lucent)

[flashtorch](https://github.com/MisaOgura/flashtorch)

[pytorch-cnn-visualizations](https://github.com/utkuozbulak/pytorch-cnn-visualizations)
[Pokemon Grad-CAM](https://qiita.com/mrok273/items/58532c06a3af3324d970)

**Comment by anthony-dipofi** [comment]
Seems interesting, I would need to read up more before implementing something like this. What would be your use case?

**Comment by koke2c95** [comment]
Thanks for being interested.
First ,I did a lot of searching work and it's none interpretable works on anime dataset at all.

The most common use is **style transfer** and  **image transfer** more stable **image synthesize**, like [deepdream](https://microscope.openai.com/models/inceptionv1?models.caricature.cossim_pow=2.0&models.caricature.image=car&models.technique=caricature),[feature_vis](https://microscope.openai.com/models/inceptionv1/mixed4a_0?models.op.feature_vis.type=channel&models.op.technique=feature_vis)
**this may very helpful for these task for handcraft model design! in anime datasets**

AND
it alse be helpful to do interpretable [on the dataset](https://microscope.openai.com/models/inceptionv1/mixed4a_0?models.op.technique=dataset_examples)
danbooru2019 dataset has **3.69m images with 108m tag** without deep cleanup, deep design([imagenet](https://arxiv.org/abs/2006.07159)), just from danbooru
